package tui

import (
	"context"
	"fmt"
	"strings"
	"unicode"

	tea "github.com/charmbracelet/bubbletea"

	"dev-forge-mcp/internal/tools"
	"dev-forge-mcp/internal/tools/codetools"
	"dev-forge-mcp/internal/tools/codetools/transform"
)

var codeToolsOps = []string{
	"JSON to Types",
	"JS/TS AST Explorer",
	"Code Formatter",
	"Code Metrics",
	"Template Renderer",
}

type codeToolsModel struct {
	phase    int
	opIdx    int
	fieldIdx int
	fields   []fieldDef
	values   map[string]string
	inputBuf string
	result   string
	isError  bool
	goHome   bool
	srv      *tools.Server
}

func newCodeToolsModel(srv *tools.Server) codeToolsModel {
	return codeToolsModel{srv: srv, values: make(map[string]string)}
}

func (m codeToolsModel) Init() tea.Cmd { return nil }

func (m codeToolsModel) Update(msg tea.Msg) (codeToolsModel, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.KeyMsg:
		switch m.phase {
		case 0:
			return m.updatePhase0(msg)
		case 1:
			return m.updatePhase1(msg)
		case 2:
			return m.updatePhase2(msg)
		}
	}
	return m, nil
}

func (m codeToolsModel) updatePhase0(msg tea.KeyMsg) (codeToolsModel, tea.Cmd) {
	switch msg.String() {
	case "up", "k":
		if m.opIdx > 0 {
			m.opIdx--
		}
	case "down", "j":
		if m.opIdx < len(codeToolsOps)-1 {
			m.opIdx++
		}
	case "enter", " ":
		m.fields = codeToolsFields(m.opIdx)
		m.fieldIdx = 0
		m.inputBuf = ""
		m.values = make(map[string]string)
		m.phase = 1
	case "esc", "q":
		m.goHome = true
	}
	return m, nil
}

func (m codeToolsModel) updatePhase1(msg tea.KeyMsg) (codeToolsModel, tea.Cmd) {
	switch msg.String() {
	case "esc":
		if m.fieldIdx == 0 {
			m.phase = 0
			m.inputBuf = ""
		} else {
			m.fieldIdx--
			m.inputBuf = m.values[m.fields[m.fieldIdx].key]
		}
	case "enter":
		m.values[m.fields[m.fieldIdx].key] = m.inputBuf
		if m.fieldIdx == len(m.fields)-1 {
			res := m.execute()
			m.result = res
			m.isError = strings.Contains(res, `"error"`)
			m.phase = 2
			return m, nil
		}
		m.fieldIdx++
		m.inputBuf = m.values[m.fields[m.fieldIdx].key]
	case "backspace", "ctrl+h":
		if len(m.inputBuf) > 0 {
			runes := []rune(m.inputBuf)
			m.inputBuf = string(runes[:len(runes)-1])
		}
	default:
		for _, r := range msg.Runes {
			if unicode.IsPrint(r) {
				m.inputBuf += string(r)
			}
		}
	}
	return m, nil
}

func (m codeToolsModel) updatePhase2(msg tea.KeyMsg) (codeToolsModel, tea.Cmd) {
	switch msg.String() {
	case "enter", "esc", "q":
		m.phase = 0
		m.inputBuf = ""
		m.values = make(map[string]string)
	}
	return m, nil
}

func (m codeToolsModel) execute() string {
	ctx := context.Background()
	switch m.opIdx {
	case 0: // JSON to Types
		return transform.JSONToTypes(ctx, transform.JSONToTypesInput{
			JSON:     m.values["json"],
			Language: m.values["language"],
			RootName: m.values["root_name"],
		})
	case 1: // JS/TS AST Explorer
		return transform.ASTExplore(ctx, transform.ASTExploreInput{
			Code:     m.values["code"],
			Language: m.values["language"],
		})
	case 2: // Code Formatter
		return codetools.Format(ctx, codetools.FormatInput{
			Code:     m.values["code"],
			Language: m.values["language"],
		})
	case 3: // Code Metrics
		return codetools.Metrics(ctx, codetools.MetricsInput{
			Code:     m.values["code"],
			Language: m.values["language"],
		})
	case 4: // Template Renderer
		return codetools.Template(ctx, codetools.TemplateInput{
			Template: m.values["template"],
			Context:  m.values["context"],
			Engine:   m.values["engine"],
		})
	}
	return `{"error":"unknown operation"}`
}

func codeToolsFields(opIdx int) []fieldDef {
	switch opIdx {
	case 0:
		return []fieldDef{
			{"json", "JSON", true, "raw JSON payload", false},
			{"language", "Language", true, "typescript | go | rust", false},
			{"root_name", "Root Name", false, "root type name (default: AutoGenerated)", false},
		}
	case 1:
		return []fieldDef{
			{"code", "Code", true, "JavaScript or TypeScript source", false},
			{"language", "Language", false, "javascript | typescript (default: javascript)", false},
		}
	case 2:
		return []fieldDef{
			{"code", "Code", true, "source code to format", false},
			{"language", "Language", true, "go | typescript | json | html | css", false},
		}
	case 3:
		return []fieldDef{
			{"code", "Code", true, "source code to analyze", false},
			{"language", "Language", false, "go | typescript | python | generic (default: generic)", false},
		}
	case 4:
		return []fieldDef{
			{"template", "Template", true, "Go template or Mustache template string", false},
			{"context", "Context (JSON)", true, `JSON object with variable bindings, e.g. {"name":"World"}`, false},
			{"engine", "Engine", false, "go | mustache (default: go)", false},
		}
	}
	return nil
}

func (m codeToolsModel) View() string {
	switch m.phase {
	case 0:
		return m.viewPhase0()
	case 1:
		return m.viewPhase1()
	case 2:
		return m.viewPhase2()
	}
	return ""
}

func (m codeToolsModel) viewPhase0() string {
	var b strings.Builder
	b.WriteString(titleStyle.Render("◆ Code Utilities") + "\n\n")
	b.WriteString(normalStyle.Render("Select operation:") + "\n")
	for i, op := range codeToolsOps {
		if i == m.opIdx {
			b.WriteString(selectedStyle.Render(fmt.Sprintf("> %s", op)) + "\n")
		} else {
			b.WriteString(normalStyle.Render(fmt.Sprintf("  %s", op)) + "\n")
		}
	}
	b.WriteString("\n" + helpStyle.Render("↑/↓ navigate • Enter select • Esc back"))
	return b.String()
}

func (m codeToolsModel) viewPhase1() string {
	if m.fieldIdx >= len(m.fields) {
		return ""
	}
	field := m.fields[m.fieldIdx]
	var b strings.Builder
	b.WriteString(titleStyle.Render(fmt.Sprintf("◆ %s (%d/%d)", codeToolsOps[m.opIdx], m.fieldIdx+1, len(m.fields))) + "\n\n")
	b.WriteString(normalStyle.Render(field.label) + "\n")
	if field.hint != "" {
		b.WriteString(dimStyle.Render(field.hint) + "\n")
	}
	b.WriteString("\n")
	b.WriteString(boxStyle.Render(m.inputBuf+"_") + "\n")
	b.WriteString("\n" + helpStyle.Render("Esc back • Enter confirm"))
	return b.String()
}

func (m codeToolsModel) viewPhase2() string {
	var b strings.Builder
	if m.isError {
		b.WriteString(errorStyle.Render("✗ Error") + "\n\n")
		b.WriteString(errorStyle.Render(m.result) + "\n")
	} else {
		b.WriteString(successStyle.Render("✓ Result") + "\n\n")
		b.WriteString(normalStyle.Render(m.result) + "\n")
	}
	b.WriteString("\n" + helpStyle.Render("Enter/Esc → back to operations"))
	return b.String()
}
