// Package transform implements code transformation and exploration utilities.
package transform

import (
	"context"
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"strings"
	"unicode"
)

func errJSON(msg string) string {
	b, _ := json.Marshal(map[string]string{"error": msg})
	return string(b)
}

func resultJSON(v any) string {
	b, err := json.Marshal(v)
	if err != nil {
		return errJSON("marshal failed: " + err.Error())
	}
	return string(b)
}

// JSONToTypesInput holds input for the JSON-to-types utility.
type JSONToTypesInput struct {
	JSON     string `json:"json"`
	Language string `json:"language"`  // typescript | go | rust
	RootName string `json:"root_name"` // default: AutoGenerated
}

// JSONToTypesOutput holds generated code.
type JSONToTypesOutput struct {
	Language string `json:"language"`
	RootName string `json:"root_name"`
	Code     string `json:"code"`
}

// JSONToTypes generates TypeScript interfaces, Go structs, or Rust structs from raw JSON.
func JSONToTypes(_ context.Context, in JSONToTypesInput) string {
	if strings.TrimSpace(in.JSON) == "" {
		return errJSON("json is required")
	}

	lang := normalizeLang(in.Language)
	if lang == "" {
		return errJSON("language must be one of: typescript, go, rust")
	}

	rootName := toPascal(defaultIfEmpty(in.RootName, "AutoGenerated"))

	var raw any
	if err := json.Unmarshal([]byte(in.JSON), &raw); err != nil {
		return errJSON("invalid json: " + err.Error())
	}

	var code string
	var err error
	switch lang {
	case "typescript":
		code, err = generateTypeScript(raw, rootName)
	case "go":
		code, err = generateGo(raw, rootName)
	case "rust":
		code, err = generateRust(raw, rootName)
	}
	if err != nil {
		return errJSON(err.Error())
	}

	return resultJSON(JSONToTypesOutput{
		Language: lang,
		RootName: rootName,
		Code:     strings.TrimSpace(code),
	})
}

type genCtx struct {
	defs       map[string]string
	order      []string
	nameCount  map[string]int
	needsJSON  bool
	needsSerde bool
}

func newGenCtx() *genCtx {
	return &genCtx{defs: map[string]string{}, order: []string{}, nameCount: map[string]int{}}
}

func (g *genCtx) uniqueName(base string) string {
	if base == "" {
		base = "AutoGenerated"
	}
	if _, ok := g.defs[base]; !ok {
		return base
	}
	g.nameCount[base]++
	return fmt.Sprintf("%s%d", base, g.nameCount[base]+1)
}

func (g *genCtx) addDef(name, body string) {
	if _, ok := g.defs[name]; ok {
		return
	}
	g.defs[name] = body
	g.order = append(g.order, name)
}

func generateTypeScript(raw any, rootName string) (string, error) {
	ctx := newGenCtx()
	rootType := tsType(raw, rootName, ctx)

	var out strings.Builder
	for _, n := range ctx.order {
		out.WriteString(ctx.defs[n])
		out.WriteString("\n\n")
	}
	if rootType != rootName {
		out.WriteString(fmt.Sprintf("export type %s = %s;\n", rootName, rootType))
	}
	return strings.TrimSpace(out.String()), nil
}

func tsType(v any, hint string, ctx *genCtx) string {
	switch t := v.(type) {
	case map[string]any:
		name := toPascal(hint)
		if name == "" {
			name = "AutoGenerated"
		}
		name = ctx.uniqueName(name)
		keys := sortedKeys(t)
		var body strings.Builder
		body.WriteString(fmt.Sprintf("export interface %s {\n", name))
		for _, k := range keys {
			fieldType := tsType(t[k], toPascal(k), ctx)
			body.WriteString(fmt.Sprintf("  %s: %s;\n", k, fieldType))
		}
		body.WriteString("}")
		ctx.addDef(name, body.String())
		return name
	case []any:
		if len(t) == 0 {
			return "any[]"
		}
		types := map[string]bool{}
		for _, item := range t {
			types[tsType(item, singular(hint)+"Item", ctx)] = true
		}
		if len(types) == 1 {
			for k := range types {
				return k + "[]"
			}
		}
		joined := mapKeysSorted(types)
		return "(" + strings.Join(joined, " | ") + ")[]"
	case string:
		return "string"
	case bool:
		return "boolean"
	case float64:
		return "number"
	case nil:
		return "null"
	default:
		return "any"
	}
}

func generateGo(raw any, rootName string) (string, error) {
	ctx := newGenCtx()
	rootType := goType(raw, rootName, ctx)

	var out strings.Builder
	for _, n := range ctx.order {
		out.WriteString(ctx.defs[n])
		out.WriteString("\n\n")
	}
	if rootType != rootName {
		out.WriteString(fmt.Sprintf("type %s %s\n", rootName, rootType))
	}
	return strings.TrimSpace(out.String()), nil
}

func goType(v any, hint string, ctx *genCtx) string {
	switch t := v.(type) {
	case map[string]any:
		name := ctx.uniqueName(toPascal(hint))
		keys := sortedKeys(t)
		var body strings.Builder
		body.WriteString(fmt.Sprintf("type %s struct {\n", name))
		for _, k := range keys {
			ft := goType(t[k], toPascal(k), ctx)
			body.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", toPascal(k), ft, k))
		}
		body.WriteString("}")
		ctx.addDef(name, body.String())
		return name
	case []any:
		if len(t) == 0 {
			return "[]interface{}"
		}
		first := t[0]
		et := goType(first, singular(hint)+"Item", ctx)
		for _, item := range t[1:] {
			if goType(item, singular(hint)+"Item", ctx) != et {
				return "[]interface{}"
			}
		}
		return "[]" + et
	case string:
		return "string"
	case bool:
		return "bool"
	case float64:
		return "float64"
	case nil:
		return "interface{}"
	default:
		return "interface{}"
	}
}

func generateRust(raw any, rootName string) (string, error) {
	ctx := newGenCtx()
	rootType := rustType(raw, rootName, ctx)

	var out strings.Builder
	out.WriteString("use serde::{Deserialize, Serialize};\n")
	if ctx.needsJSON {
		out.WriteString("use serde_json::Value;\n")
	}
	out.WriteString("\n")

	for _, n := range ctx.order {
		out.WriteString(ctx.defs[n])
		out.WriteString("\n\n")
	}
	if rootType != rootName {
		out.WriteString(fmt.Sprintf("pub type %s = %s;\n", rootName, rootType))
	}

	return strings.TrimSpace(out.String()), nil
}

func rustType(v any, hint string, ctx *genCtx) string {
	switch t := v.(type) {
	case map[string]any:
		name := ctx.uniqueName(toPascal(hint))
		keys := sortedKeys(t)
		var body strings.Builder
		body.WriteString("#[derive(Debug, Clone, Serialize, Deserialize)]\n")
		body.WriteString(fmt.Sprintf("pub struct %s {\n", name))
		for _, k := range keys {
			rName := toSnake(k)
			if rName == "" {
				rName = "field"
			}
			if rName != k {
				body.WriteString(fmt.Sprintf("    #[serde(rename = \"%s\")]\n", k))
			}
			ft := rustType(t[k], toPascal(k), ctx)
			body.WriteString(fmt.Sprintf("    pub %s: %s,\n", rName, ft))
		}
		body.WriteString("}")
		ctx.addDef(name, body.String())
		return name
	case []any:
		if len(t) == 0 {
			ctx.needsJSON = true
			return "Vec<Value>"
		}
		et := rustType(t[0], singular(hint)+"Item", ctx)
		for _, item := range t[1:] {
			if rustType(item, singular(hint)+"Item", ctx) != et {
				ctx.needsJSON = true
				return "Vec<Value>"
			}
		}
		return "Vec<" + et + ">"
	case string:
		return "String"
	case bool:
		return "bool"
	case float64:
		return "f64"
	case nil:
		ctx.needsJSON = true
		return "Option<Value>"
	default:
		ctx.needsJSON = true
		return "Value"
	}
}

// ASTExploreInput holds input for the JS/TS AST explorer utility.
type ASTExploreInput struct {
	Code     string `json:"code"`
	Language string `json:"language"` // javascript | typescript
}

// ASTNode is a lightweight AST-like node.
type ASTNode struct {
	Type     string    `json:"type"`
	Name     string    `json:"name,omitempty"`
	Line     int       `json:"line,omitempty"`
	Children []ASTNode `json:"children,omitempty"`
}

// ASTExploreOutput is the AST explorer output schema.
type ASTExploreOutput struct {
	Language string         `json:"language"`
	AST      ASTNode        `json:"ast"`
	Summary  map[string]int `json:"summary"`
}

// ASTExplore builds a lightweight AST outline for JavaScript/TypeScript code.
func ASTExplore(_ context.Context, in ASTExploreInput) string {
	if strings.TrimSpace(in.Code) == "" {
		return errJSON("code is required")
	}
	lang := strings.ToLower(strings.TrimSpace(in.Language))
	if lang == "" {
		lang = "javascript"
	}
	if lang != "javascript" && lang != "typescript" && lang != "js" && lang != "ts" {
		return errJSON("language must be javascript or typescript")
	}
	if lang == "js" {
		lang = "javascript"
	}
	if lang == "ts" {
		lang = "typescript"
	}

	root, summary := buildASTOutline(in.Code)
	return resultJSON(ASTExploreOutput{Language: lang, AST: root, Summary: summary})
}

type astInternal struct {
	node       ASTNode
	children   []*astInternal
	blockDepth int
}

var (
	reClass    = regexp.MustCompile(`^\s*(?:export\s+)?class\s+([A-Za-z_][A-Za-z0-9_]*)`)
	reFunction = regexp.MustCompile(`^\s*(?:export\s+)?(?:async\s+)?function\s+([A-Za-z_][A-Za-z0-9_]*)`)
	reVar      = regexp.MustCompile(`^\s*(const|let|var)\s+([A-Za-z_][A-Za-z0-9_]*)`)
	reImport   = regexp.MustCompile(`^\s*import\b`)
	reExport   = regexp.MustCompile(`^\s*export\b`)
)

func buildASTOutline(code string) (ASTNode, map[string]int) {
	root := &astInternal{node: ASTNode{Type: "Program"}, blockDepth: 0}
	stack := []*astInternal{root}
	braceDepth := 0
	summary := map[string]int{}

	lines := strings.Split(code, "\n")
	for i, line := range lines {
		trim := strings.TrimSpace(line)
		if trim == "" {
			open, close := strings.Count(line, "{"), strings.Count(line, "}")
			braceDepth += open - close
			for len(stack) > 1 && braceDepth < stack[len(stack)-1].blockDepth {
				stack = stack[:len(stack)-1]
			}
			continue
		}

		typ, name := detectDeclaration(trim)
		if typ != "" {
			n := &astInternal{node: ASTNode{Type: typ, Name: name, Line: i + 1}}
			parent := stack[len(stack)-1]
			parent.children = append(parent.children, n)
			summary[typ]++

			openCount := strings.Count(line, "{")
			closeCount := strings.Count(line, "}")
			if openCount > closeCount {
				n.blockDepth = braceDepth + 1
				stack = append(stack, n)
			}
		}

		open, close := strings.Count(line, "{"), strings.Count(line, "}")
		braceDepth += open - close
		for len(stack) > 1 && braceDepth < stack[len(stack)-1].blockDepth {
			stack = stack[:len(stack)-1]
		}
	}

	return collapseAST(root), summary
}

func detectDeclaration(line string) (typ, name string) {
	if m := reClass.FindStringSubmatch(line); len(m) == 2 {
		return "ClassDeclaration", m[1]
	}
	if m := reFunction.FindStringSubmatch(line); len(m) == 2 {
		return "FunctionDeclaration", m[1]
	}
	if m := reVar.FindStringSubmatch(line); len(m) == 3 {
		if strings.Contains(line, "=>") {
			return "ArrowFunctionVariable", m[2]
		}
		return "VariableDeclaration", m[2]
	}
	if reImport.MatchString(line) {
		return "ImportDeclaration", ""
	}
	if reExport.MatchString(line) {
		return "ExportDeclaration", ""
	}
	return "", ""
}

func collapseAST(in *astInternal) ASTNode {
	out := in.node
	if len(in.children) == 0 {
		return out
	}
	out.Children = make([]ASTNode, 0, len(in.children))
	for _, c := range in.children {
		out.Children = append(out.Children, collapseAST(c))
	}
	return out
}

func normalizeLang(v string) string {
	s := strings.ToLower(strings.TrimSpace(v))
	switch s {
	case "typescript", "ts":
		return "typescript"
	case "go", "golang":
		return "go"
	case "rust", "rs":
		return "rust"
	default:
		return ""
	}
}

func sortedKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func mapKeysSorted(m map[string]bool) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func defaultIfEmpty(v, fallback string) string {
	if strings.TrimSpace(v) == "" {
		return fallback
	}
	return v
}

func singular(v string) string {
	v = strings.TrimSpace(v)
	if strings.HasSuffix(v, "s") && len(v) > 1 {
		return v[:len(v)-1]
	}
	return v
}

func toPascal(v string) string {
	words := splitWords(v)
	for i := range words {
		if words[i] == "" {
			continue
		}
		words[i] = strings.ToUpper(words[i][:1]) + strings.ToLower(words[i][1:])
	}
	res := strings.Join(words, "")
	if res == "" {
		return "AutoGenerated"
	}
	if unicode.IsDigit(rune(res[0])) {
		return "N" + res
	}
	return res
}

func toSnake(v string) string {
	words := splitWords(v)
	for i := range words {
		words[i] = strings.ToLower(words[i])
	}
	res := strings.Join(words, "_")
	if res == "" {
		return "field"
	}
	if unicode.IsDigit(rune(res[0])) {
		return "n_" + res
	}
	return res
}

func splitWords(v string) []string {
	var words []string
	var current []rune
	for _, r := range v {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			if len(current) > 0 && unicode.IsUpper(r) && unicode.IsLower(current[len(current)-1]) {
				words = append(words, string(current))
				current = []rune{r}
			} else {
				current = append(current, r)
			}
		} else if len(current) > 0 {
			words = append(words, string(current))
			current = nil
		}
	}
	if len(current) > 0 {
		words = append(words, string(current))
	}
	if len(words) == 0 {
		return []string{"auto", "generated"}
	}
	return words
}
